services:
  # postgres db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB: fbt
      - POSTGRES_USER: user
      - POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data: